---
- name: Restart zabbix-server
  ansible.builtin.service:
    name: zabbix-server
    state: restarted
  become: true

- name: Restart zabbix-agent2
  ansible.builtin.service:
    name: zabbix-agent2
    state: restarted
  become: true

- name: Restart apache2
  ansible.builtin.service:
    name: apache2
    state: restarted
  become: true
